### ISSUE TITLE
PostCSS version is 4.1.16, but postcss-flexibility uses 5.0.14 error

### ISSUE THREAD

**Issue by Designer023** [7rulnik/postcss-flexibility#27]
Hi,

I'm having issues getting the plugin to work. I have updated post CSS to the latest version in my project (6.1.1) and I'm still getting the errors:
Your current PostCSS version is 4.1.16, but postcss-flexibility uses 5.0.14. Perhaps this is the source of the error below.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: css.walkRules is not a function
    at /path/node_modules/postcss-flexibility/index.es5.js:15:7
    at LazyResult.run (/path/project/front-end/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:197:24)
    at /path/project/front-end/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:110:37
    at LazyResult.asyncTick (/path/project/front-end/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:124:15)
    at /path/project/front-end/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:122:27
    at LazyResult.asyncTick (/path/project/front-end/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:124:15)
    at /path/project/front-end/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:122:27
    at LazyResult.asyncTick (/path/project/front-end/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:124:15)
    at /path/project/front-end/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:122:27
    at LazyResult.asyncTick (/path/project/front-end/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:124:15)

Process finished with exit code 1

```

All other PostCSS plugins are working ok, so not sure what's happening. Any ideas? Thank you

**Comment by Designer023** [comment]
I'm an idiot. 2 package json files in my repo (big project) wrong one had the right version of postCSS. That'll teach me!
